# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=30)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
